[workspace]
resolver = "1"
members = [
    "lib/chrontext",
    "lib/virtualization",
    "lib/postgres",
    "lib/virtualized_query",
    "py_chrontext",
    "lib/flight",
    "lib/sparql_database"
]

[workspace.dependencies]
#spargebra = { path = "../maplib/lib/spargebra", features = ["rdf-star"]}
#query_processing = { path = "../maplib/lib/query_processing"}
#pydf_io = { path = "../maplib/lib/pydf_io"}
#representation = { path = "../maplib/lib/representation", features = ["rdf-star"]}
#templates = { path = "../maplib/lib/templates"}
spargebra = { git = "https://github.com/DataTreehouse/maplib", rev="0b0c67e767cc1c67156bde273a1a717b93c30a42", features = ["rdf-star"]}
query_processing = { git = "https://github.com/DataTreehouse/maplib", rev="0b0c67e767cc1c67156bde273a1a717b93c30a42" }
pydf_io = { git = "https://github.com/DataTreehouse/maplib", rev="0b0c67e767cc1c67156bde273a1a717b93c30a42" }
representation = { git = "https://github.com/DataTreehouse/maplib", rev="0b0c67e767cc1c67156bde273a1a717b93c30a42", features = ["rdf-star"] }
templates = { git = "https://github.com/DataTreehouse/maplib", rev="0b0c67e767cc1c67156bde273a1a717b93c30a42" }


sparesults = { version = "0.2.3", features = ["rdf-star"] }
oxrdf = { version = "0.2.2", features = ["rdf-star"] }

polars = "0.45.1"
tonic = "0.12.3"
tokio = "1.32.1"
arrow-flight = "53.1.0"
futures = "0.3.31"
bincode = "1.3.3"
log = "0.4.21"
pyo3 = "0.22.6"
reqwest = "0.12.5"
env_logger = "0.11.3"
thiserror = "1.0.58"
async-recursion = "1.1.0"
async-trait = "0.1.81"
chrono = "0.4.37"
filesize = "0.2.0"
serde = "1.0.203"
serde_json = "1.0.117"
secrecy = "=0.10.3"
backoff = "0.4.0"
gcp-bigquery-client = "0.23.0"
rayon = "1.10.0"
opcua = {version="0.12.0", features = ["vendored-openssl"]}
url = "2.5.2"
uuid = {version = "1.10.0", features = ["fast-rng", "v4"]}
rustls = "0.23.18"

