[workspace]
resolver = "1"
members = [
    "chrontext",
    "timeseries_outpost",
    "postgres",
    "timeseries_query"]

[patch.crates-io]
polars = { git = 'https://github.com/pola-rs/polars.git', rev = "805acd81cfed82248d34fa69875cbe04730f74ce" }
polars-core = { git = 'https://github.com/pola-rs/polars.git', rev = "805acd81cfed82248d34fa69875cbe04730f74ce" }
polars-utils = { git = 'https://github.com/pola-rs/polars.git', rev = "805acd81cfed82248d34fa69875cbe04730f74ce" }

[workspace.dependencies]
polars = { version = "0.40.0" }
tokio = { version = "1.32.1", features = ["rt-multi-thread", "rt"] }
log = "0.4.21"
#spargebra = { path = "../spargebra", features = ["rdf-star"]}
spargebra = { git = "https://github.com/DataTreehouse/spargebra", features = ["rdf-star"], tag = "v0.2.8" }
#query_processing = { path = "../query_processing" }
query_processing = { git = "https://github.com/DataTreehouse/query_processing", tag="v0.3.8"}
#representation = { path = "../representation" }
representation = { git = "https://github.com/DataTreehouse/representation", tag="v0.6.7"}
sparesults = { version = "0.1.8" }
oxrdf = { version = "0.1.7" }
reqwest = { version = "0.12.3", features = ["stream"] }
env_logger = "0.11.3"
thiserror = "1.0.58"
base64 = "0.22.0"
async-recursion = "1.1.0"
async-trait = "0.1.80"
crossbeam = { version = "0.8.2" }
oxigraph = "0.3.22"
chrono = { version = "0.4.37", features = ["clock"] }
filesize = "0.2.0"
futures = "0.3.30"
tokio-stream = "0.1.15"
serde = "1.0.203"
serde_json = "1.0.117"
