[workspace]
resolver = "1"
members = [
    "lib/chrontext",
    "lib/virtualization",
    "lib/postgres",
    "lib/virtualized_query",
    "py_chrontext",
    "lib/flight",
    "lib/sparql_database"
]

[workspace.dependencies]
#spargebra = { path = "../maplib/lib/spargebra", features = ["rdf-star"]}
#query_processing = { path = "../maplib/lib/query_processing"}
#pydf_io = { path = "../maplib/lib/pydf_io"}
#representation = { path = "../maplib/lib/representation", features = ["rdf-star"]}
#templates = { path = "../maplib/lib/templates"}
spargebra = { git = "https://github.com/DataTreehouse/maplib", rev="fb49d7fff2e065baea3952762849a2f83db5ab3d", features = ["rdf-star"]}
query_processing = { git = "https://github.com/DataTreehouse/maplib", rev="fb49d7fff2e065baea3952762849a2f83db5ab3d" }
pydf_io = { git = "https://github.com/DataTreehouse/maplib", rev="fb49d7fff2e065baea3952762849a2f83db5ab3d" }
representation = { git = "https://github.com/DataTreehouse/maplib", rev="fb49d7fff2e065baea3952762849a2f83db5ab3d", features = ["rdf-star"] }
templates = { git = "https://github.com/DataTreehouse/maplib", rev="fb49d7fff2e065baea3952762849a2f83db5ab3d" }


sparesults = { version = "0.2.2", features = ["rdf-star"] }
oxrdf = { version = "0.2.2", features = ["rdf-star"] }
oxrdfio = { version= "0.1.2", features = ["rdf-star"] }

polars = "0.41.3"
tonic = "0.12.3"
tokio = "1.32.1"
arrow-flight = "53.1.0"
futures = "0.3.31"
bincode = "1.3.3"
log = "0.4.21"
pyo3 = "0.22.5"
reqwest = "0.12.5"
env_logger = "0.11.3"
thiserror = "1.0.58"
async-recursion = "1.1.0"
async-trait = "0.1.81"
chrono = "0.4.37"
filesize = "0.2.0"
serde = "1.0.203"
serde_json = "1.0.117"
secrecy = "=0.10.3"
backoff = "0.4.0"
gcp-bigquery-client = "0.23.0"
rayon = "1.10.0"
opcua = {version="0.12.0", features = ["vendored-openssl"]}
url = "2.5.2"
uuid = {version = "1.10.0", features = ["fast-rng", "v4"]}
# Workaround for problem compiling polars
# https://github.com/pola-rs/polars/issues/19063
hashbrown = { version = "0.14.5", features = ["raw"] }
rustls = "0.23.16"

[patch.crates-io]
#polars = { git = "https://github.com/pola-rs/polars.git",  rev = "0c2b5d82fd2726df7d7b318e5c21581a27fffdba"}
#polars-core = { git = "https://github.com/pola-rs/polars.git",  rev = "0c2b5d82fd2726df7d7b318e5c21581a27fffdba"}
