[workspace]
resolver = "1"
members = [
    "lib/bigquery-polars",
    "lib/chrontext",
    "lib/virtualization",
    "lib/postgres",
    "lib/virtualized_query",
    "py_chrontext"
]

[workspace.dependencies]
#spargebra = { path = "../maplib/lib/spargebra", features = ["rdf-star"]}
#query_processing = { path = "../maplib/lib/query_processing"}
#pydf_io = { path = "../maplib/lib/pydf_io"}
#representation = { path = "../maplib/lib/representation", features = ["rdf-star"]}
#templates = { path = "../maplib/lib/templates"}

spargebra = { git = "https://github.com/DataTreehouse/maplib", rev="32ad6862c3081af5186c65a63f780121ce0d39bc", features = ["rdf-star"]}
query_processing = { git = "https://github.com/DataTreehouse/maplib", rev="32ad6862c3081af5186c65a63f780121ce0d39bc" }
pydf_io = { git = "https://github.com/DataTreehouse/maplib", rev="32ad6862c3081af5186c65a63f780121ce0d39bc" }
representation = { git = "https://github.com/DataTreehouse/maplib", rev="32ad6862c3081af5186c65a63f780121ce0d39bc", features = ["rdf-star"] }
templates = { git = "https://github.com/DataTreehouse/maplib", rev="32ad6862c3081af5186c65a63f780121ce0d39bc" }


sparesults = { version = "0.2.0-alpha.5", features = ["rdf-star"] }
oxrdf = { version = "0.2.0-alpha.5", features = ["rdf-star"] }
oxigraph = "0.4.0-alpha.7"

polars = "0.41.3"
tokio = "1.32.1"
log = "0.4.21"
pyo3 = "0.22.0"
reqwest = "0.12.3"
env_logger = "0.11.3"
thiserror = "1.0.58"
async-recursion = "1.1.0"
async-trait = "0.1.81"
chrono = "0.4.37"
filesize = "0.2.0"
serde = "1.0.203"
serde_json = "1.0.117"
backoff = "0.4.0"
gcp-bigquery-client = "0.20.0"
rayon = "1.10.0"
opcua = {version="0.12.0", features = ["vendored-openssl"]}
url = "2.5.2"

[patch.crates-io]
oxrdf = { git = 'https://github.com/oxigraph/oxigraph.git', rev = "1e08089454a9aa8b3f66f4a422aed27e73faae84"}
oxttl = { git = 'https://github.com/oxigraph/oxigraph.git', rev = "1e08089454a9aa8b3f66f4a422aed27e73faae84"}
oxrdfio = { git = 'https://github.com/oxigraph/oxigraph.git', rev = "1e08089454a9aa8b3f66f4a422aed27e73faae84"}
oxigraph = { git = 'https://github.com/oxigraph/oxigraph.git', rev = "1e08089454a9aa8b3f66f4a422aed27e73faae84"}
sparesults = { git = 'https://github.com/oxigraph/oxigraph.git', rev = "1e08089454a9aa8b3f66f4a422aed27e73faae84"}

