[package]
name = "arrow_python_utils"
version = "0.2.4"
edition = "2021"

[dependencies]
pyo3 = {version = "0.16.5", features = ["extension-module"]}
polars-core = {version="0.31.1"}
thiserror="1.0.31"
simple-error = "0.2.3"
