[package]
name = "arrow_python_utils"
version = "0.3.1"
edition = "2021"

[dependencies]
pyo3 = {version = "0.19.2", features = ["extension-module"]}
polars-core = {version="0.32.1"}
thiserror="1.0.31"
simple-error = "0.2.3"
