name: Security audit
on:
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'

env:
  CARGO_TERM_COLOR: always
  RUST_TOOLCHAIN: nightly-2025-03-07

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout chrontext
        uses: actions/checkout@v4

      - name: Audit
        uses: rustsec/audit-check@v1.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}