name: Rust tests

on:
  push:
    branches: [ main, feature/*, bugfix/* ]
  pull_request:
    branches: [ main, feature/*, bugfix/* ]

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: debug
  RUST_TOOLCHAIN: nightly-2024-06-23

jobs:
  build_and_test:
    runs-on:
      group: ubuntu_runners

    steps:
    - uses: actions/checkout@v3

    - name: Upgrade rust with nightly, install build-essential, pull oxigraph and dremio image
      run: |
        rustup update
        rustup toolchain install ${{ env.RUST_TOOLCHAIN }}
        rustup default ${{ env.RUST_TOOLCHAIN }}
        
        docker pull oxigraph/oxigraph:v0.3.8

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}

    - name: Build
      run: cargo build --features=opcua --verbose --all
    - name: Run rust tests
      run: cargo test --features=opcua --verbose --all
